### ISSUE TITLE
Cannot import imsave from scipy.misc

### ISSUE THREAD

**Issue by yousiki** [overflocat/fast-neural-style-keras#1]
Many thanks for your code, but I met the error when tried to run it.
After searching on google, I found that `imsave` was removed from `scipy.misc`. And it's supposed that `scipy.misc.imsave` should be replaced by `imageio.imwrite`.
I've modified the code and that works.
Maybe you can use 3 min to change your code, such as 
``` python
# from scipy.misc import imsave
from imageio import imwrite
imsave = imwrite
```
Thanks again.

**Comment by overflocat** [comment]
Sorry about that, this project has not been updated for a whole year. When I implemented it, the new version of Scipy did not come out.
Now it should be fixed.
